<?php

namespace App\Models;

use App\Http\Controllers\BooksController;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Laravel\Scout\Searchable;

class Books extends Model
{
    protected $fillable = ['title','isbn','genre_id','author_id','description','publisher_id','genre_id','created_at','updated_at'];
    use HasFactory;
    use Searchable;
    protected $with = [
        'author:id,name',
        'publisher:id,name',
        'genre:id,name'
    ];
    public function toSearchableArray()
    {
        return [
            'title' => $this->title,
            'isbn' => $this->isbn,
            'genre_id' => $this->genre_id,
            'author_id' => $this->author_id,
            'publisher_id' => $this->publisher_id,
            'published_on' => $this->published_on,
            'author' => $this->author->name,
            'publisher' => $this->publisher->name,
            'genre' => $this->genre->name,
        ];
    }


    public function genre(): HasOne
    {
        return $this->hasOne(Genre::class,'id','genre_id');
    }
    public function author(): HasOne
    {
        return $this->hasOne(Author::class,'id','author_id');
    }
    public function publisher() : HasOne
    {
        return $this->hasOne(Publisher::class,'id','publisher_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::updated(function ($item){
            $bookController = new BooksController();
            $bookController->doDirtyThings();
        });
    }


}
